---
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lnbnatera/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true lnbnatera/docker-react npm run test
...